### ISSUE TITLE
panoptic.py error

### ISSUE THREAD

**Issue by Aaron20127** [JiangWenPL/multiperson#10]
hello, I use panoptic.py to get test dataset, But I get an error bellow. I don't kown what the cmu keypoints the code have used.

Connected to pydev debugger (build 201.8743.11)
  0%|                                                  | 0/1200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/icvhpc1/.pycharm_helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/icvhpc1/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/icvhpc1/bluce/code/mhmr-v1.1/experiments/release_version/multiperson/misc/preprocess_datasets/full/panoptic.py", line 166, in <module>
    process_panoptic(args.panoptic_path, args.dataset_name, args.sequence_idx)
  File "/home/icvhpc1/bluce/code/mhmr-v1.1/experiments/release_version/multiperson/misc/preprocess_datasets/full/panoptic.py", line 120, in process_panoptic
    kpts3d_J24[J24_to_J15] = skel.T
ValueError: shape mismatch: value array of shape (19,4) could not be broadcast to indexing result of shape (15,4)

**Comment by ojss** [comment]
I am facing the same problem, did you manage to find a way out? @Aaron20127
