### ISSUE TITLE
NameError: name 'ModelOutput' is not defined

### ISSUE THREAD

**Issue by Frank-Dz** [JiangWenPL/multiperson#25]
Seemks like there are something wrong with the smplx.

Does this is caused by the version difference?

```
e_folder=demo_images/ --output_folder=results/ --ckpt data/checkpoint.pt
WARNING: You are using a SMPL model, with only 10 shape coefficients.
WARNING: You are using a SMPL model, with only 10 shape coefficients.
unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer2.0.bn1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, bn1.num_batches_tracked

2021-02-15 16:49:01,865 - INFO - load checkpoint from data/checkpoint.pt
2021-02-15 16:49:02,106 - WARNING - missing keys in source state_dict: smpl_head.smpl.parents, smpl_head.smpl.faces_tensor, smpl_head.smpl.J_regressor_extra, smpl_head.loss.smpl.faces_tensor, smpl_head.loss.smpl.v_template, smpl_head.loss.smpl.lbs_weights, smpl_head.loss.smpl.J_regressor, smpl_head.loss.smpl.J_regressor_extra, smpl_head.loss.smpl.vertex_joint_selector.extra_joints_idxs, smpl_head.smpl.shapedirs, smpl_head.smpl.J_regressor, smpl_head.loss.smpl.parents, smpl_head.smpl.vertex_joint_selector.extra_joints_idxs, smpl_head.smpl.v_template, smpl_head.loss.smpl.shapedirs, smpl_head.smpl.posedirs, smpl_head.smpl.lbs_weights, smpl_head.loss.smpl.posedirs

2021-02-15 16:49:02,121 - INFO - resumed epoch 27, iter 90901
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "tools/demo.py", line 190, in <module>
    main()
  File "tools/demo.py", line 180, in main
    bbox_results, pred_results = model(**data_batch, return_loss=False)
  File "/media/frank/MyPassport/anaconda3/envs/multiperson/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/frank/MyPassport/anaconda3/envs/multiperson/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/media/frank/MyPassport/anaconda3/envs/multiperson/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/models/detectors/base.py", line 88, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/models/detectors/smpl_rcnn.py", line 419, in forward_test
    return self.simple_test(imgs, img_metas, **kwargs)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/models/detectors/smpl_rcnn.py", line 374, in simple_test
    smpl_results = self.simple_test_smpl(x, img_meta, det_bboxes, img.shape, rescale=rescale)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/models/detectors/test_mixins.py", line 189, in simple_test_smpl
    smpl_pred = self.smpl_head(smpl_feats)
  File "/media/frank/MyPassport/anaconda3/envs/multiperson/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/models/smpl_heads/smpl_head.py", line 132, in forward
    global_orient=pred_rotmat[:, 0].unsqueeze(1), pose2rot=False)
  File "/media/frank/MyPassport/anaconda3/envs/multiperson/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/frank/MyPassport/Code/HPE/multiperson/mmdetection/mmdet/models/utils/smpl/smpl.py", line 64, in forward
    output = ModelOutput(vertices=smpl_output.vertices,
NameError: name 'ModelOutput' is not defined
```

ENVs: 
**I tried to install the pkg strictly following the instructions.**
```
Ubuntu 16.04
CUDA: 10.1


Package                 Version       Location                                                
----------------------- ------------- --------------------------------------------------------
addict                  2.2.1         
argon2-cffi             20.1.0        
asn1crypto              1.2.0         
async-generator         1.10          
attrs                   20.3.0        
backcall                0.1.0         
bleach                  3.3.0         
certifi                 2019.11.28    
cffi                    1.13.0        
chardet                 3.0.4         
chumpy                  0.69          
conda                   4.8.2         
conda-package-handling  1.6.0         
ConfigArgParse          1.3           
cryptography            2.8           
cycler                  0.10.0        
Cython                  0.29.15       
decorator               4.4.2         
defusedxml              0.6.0         
entrypoints             0.3           
filelock                3.0.12        
freetype-py             2.1.0.post1   
future                  0.18.2        
gdown                   3.12.2        
h5py                    2.10.0        
idna                    2.8           
imageio                 2.8.0         
importlib-metadata      3.4.0         
install                 1.3.4         
ipdb                    0.13.2        
ipykernel               5.4.3         
ipython                 7.13.0        
ipython-genutils        0.2.0         
ipywidgets              7.6.3         
jedi                    0.16.0        
Jinja2                  2.11.3        
jsonschema              3.2.0         
jupyter-client          6.1.11        
jupyter-core            4.7.1         
jupyterlab-pygments     0.1.2         
jupyterlab-widgets      1.0.0         
kiwisolver              1.1.0         
MarkupSafe              1.1.1         
matplotlib              3.2.0rc3      
mistune                 0.8.4         
mkl-fft                 1.0.15        
mkl-random              1.1.0         
mkl-service             2.3.0         
mmcv                    0.2.10        
mmdet                   0.6.0+unknown /media/frank/MyPassport/Code/HPE/multiperson/mmdetection
mpmath                  1.2.1         
nbclient                0.5.2         
nbconvert               6.0.7         
nbformat                5.1.2         
nest-asyncio            1.5.1         
networkx                2.4           
neural-renderer-pytorch 1.1.3         
notebook                6.2.0         
numpy                   1.18.1        
olefile                 0.46          
open3d-python           0.7.0.0       
opencv-python           4.2.0.32      
packaging               20.9          
pandas                  1.0.1         
pandocfilters           1.4.3         
parso                   0.6.2         
pexpect                 4.8.0         
pickleshare             0.7.5         
Pillow                  6.1.0         
pip                     19.3.1        
prometheus-client       0.9.0         
prompt-toolkit          3.0.4         
protobuf                3.11.3        
ptyprocess              0.6.0         
pycocotools             2.0.0         
pycosat                 0.6.3         
pycparser               2.19          
pyglet                  1.5.0         
Pygments                2.6.1         
PyMCubes                0.1.2         
PyOpenGL                3.1.0         
pyOpenSSL               19.0.0        
pyparsing               2.4.6         
pypng                   0.0.20        
pyrender                0.1.36        
pyrsistent              0.17.3        
PySocks                 1.7.1         
python-dateutil         2.8.1         
pytz                    2019.3        
PyWavelets              1.1.1         
PyYAML                  5.4.1         
pyzmq                   22.0.3        
requests                2.22.0        
ruamel-yaml             0.15.46       
scikit-image            0.16.2        
scipy                   1.4.1         
sdf-pytorch             0.0.1         
seaborn                 0.10.0        
Send2Trash              1.5.0         
setuptools              41.4.0        
Shapely                 1.7.1         
six                     1.12.0        
smpl                    0.0.66        
smplx                   0.1.21        
sympy                   1.7.1         
tensorboardX            2.0           
terminado               0.9.2         
terminaltables          3.1.0         
testpath                0.4.4         
torch                   1.1.0         
torchgeometry           0.1.2         
torchvision             0.3.0         
tornado                 6.1           
tqdm                    4.36.1        
traitlets               4.3.3         
trimesh                 3.5.25        
typing-extensions       3.7.4.3       
uncertainties           3.1.5         
urllib3                 1.24.2        
wcwidth                 0.1.9         
webencodings            0.5.1         
wheel                   0.33.6        
widgetsnbextension      3.5.1         
zipp                    3.4.0         
```

**Comment by Frank-Dz** [comment]
solved by modifying the code:
multiperson/mmdetection/mmdet/models/utils/smpl/smpl.py", line 64, 
```
    output = ModelOutput(vertices=smpl_output.vertices...
```
to
```
 output = SMPLXOutput(vertices=smpl_output.vertices...
```
