### ISSUE TITLE
request for the teapot.obj used in example1.py

### ISSUE THREAD

**Issue by monacv** [JiangWenPL/multiperson#28]
Hi could you please either share the teapot.obj or the link to download to reproduce example1.py?

```
mona@goku:~/research/code/multiperson/neural_renderer$ python ./examples/example1.py
Traceback (most recent call last):
  File "./examples/example1.py", line 55, in <module>
    main()
  File "./examples/example1.py", line 31, in main
    vertices, faces = nr.load_obj(args.filename_input)
  File "/home/mona/venv/nmr/lib/python3.8/site-packages/neural_renderer/load_obj.py", line 117, in load_obj
    with open(filename_obj) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mona/research/code/multiperson/neural_renderer/examples/data/teapot.obj'

```

**Comment by monacv** [comment]
actually used the following

https://clara.io/view/3f6fcfb5-e2d5-4bb0-b1c1-55bdd6d9f2c2# downloaded Utah  teapot wavefront obj file
![example1](https://user-images.githubusercontent.com/76495162/112040925-27eb2880-8b1c-11eb-9ee2-c439eaada265.gif)
