### ISSUE TITLE
when run demo: RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by littlejiumi** [JiangWenPL/multiperson#36]
Traceback (most recent call last):
  File "tools/demo.py", line 190, in <module>
    main()
  File "tools/demo.py", line 131, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 60, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/detectors/smpl_rcnn.py", line 65, in __init__
    self.smpl_head = builder.build_head(smpl_head)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 52, in build_head
    return build(cfg, HEADS)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/smpl_heads/smpl_head.py", line 74, in __init__
    self.loss = build_loss(loss_cfg)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 56, in build_loss
    return build(cfg, LOSSES)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/root/picasso/xhzhang/multiperson/mmdetection/mmdet/models/losses/smpl_loss.py", line 107, in __init__
    anti_aliasing=False)
  File "/root/anaconda3/envs/multiperson/lib/python3.7/site-packages/neural_renderer_pytorch-1.1.3-py3.7-linux-x86_64.egg/neural_renderer/renderer.py", line 41, in __init__
    self.dist_coeffs = torch.cuda.FloatTensor([[0., 0., 0., 0., 0.]])
RuntimeError: CUDA error: unknown error

**Comment by JiangWenPL** [comment]
I didn't meet this issue in our environment.
