### ISSUE TITLE
Problem about the sdf

### ISSUE THREAD

**Issue by Kebii** [JiangWenPL/multiperson#41]
Thanks for your great work!
I want to use the sdf package in my own project and the installation process is finished. But when I am trying to run my code, I get the following error. How can I solve the problem?

Traceback (most recent call last):
  File "test.py", line 20, in <module>
    fai = get_sdf(test_faces, test_vertics)
  File "/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/sdf.py", line 25, in forward
    phi = SDFFunction.apply(phi, faces, vertices)
  File "/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/sdf.py", line 15, in forward
    return _C.sdf(phi, faces, vertices)
AttributeError: module 'sdf.csrc' has no attribute 'sdf'

The installation process:
`running install
running bdist_egg
running egg_info
creating sdf_pytorch.egg-info
writing sdf_pytorch.egg-info/PKG-INFO
writing dependency_links to sdf_pytorch.egg-info/dependency_links.txt
writing top-level names to sdf_pytorch.egg-info/top_level.txt
writing manifest file 'sdf_pytorch.egg-info/SOURCES.txt'
package init file 'sdf/csrc/__init__.py' not found (or not a regular file)
reading manifest file 'sdf_pytorch.egg-info/SOURCES.txt'
writing manifest file 'sdf_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/sdf
copying sdf/sdf.py -> build/lib.linux-x86_64-3.7/sdf
copying sdf/sdf_loss.py -> build/lib.linux-x86_64-3.7/sdf
copying sdf/__init__.py -> build/lib.linux-x86_64-3.7/sdf
running build_ext
building 'sdf.csrc' extension
creating /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7
creating /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf
creating /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf/csrc
Emitting ninja build file /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda/bin/nvcc  -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/TH -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/mnt/data3/HOME/zjx/miniconda3/include/python3.7m -c -c /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda_kernel.cu -o /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf/csrc/sdf_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
[2/2] c++ -MMD -MF /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf/csrc/sdf_cuda.o.d -pthread -B /mnt/data3/HOME/zjx/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/TH -I/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/mnt/data3/HOME/zjx/miniconda3/include/python3.7m -c -c /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp -o /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf/csrc/sdf_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:1:
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp: In function ‘at::Tensor sdf(at::Tensor, at::Tensor, at::Tensor)’:
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:3:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    3 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:197:64: note: in definition of macro ‘C10_UNLIKELY’
  197 | #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                ^~~~
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:441:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  441 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
      |       ^~~~~~~~~~~~~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:3:23: note: in expansion of macro ‘TORCH_CHECK’
    3 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:5:24: note: in expansion of macro ‘CHECK_CUDA’
    5 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:19:2: note: in expansion of macro ‘CHECK_INPUT’
   19 |  CHECK_INPUT(phi);
      |  ^~~~~~~~~~~
In file included from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:1:
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:1:
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:3:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    3 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:197:64: note: in definition of macro ‘C10_UNLIKELY’
  197 | #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                ^~~~
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:441:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  441 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
      |       ^~~~~~~~~~~~~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:3:23: note: in expansion of macro ‘TORCH_CHECK’
    3 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:5:24: note: in expansion of macro ‘CHECK_CUDA’
    5 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:20:2: note: in expansion of macro ‘CHECK_INPUT’
   20 |  CHECK_INPUT(faces);
      |  ^~~~~~~~~~~
In file included from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:1:
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
In file included from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/Device.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:7,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:1:
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:3:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
    3 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/macros/Macros.h:197:64: note: in definition of macro ‘C10_UNLIKELY’
  197 | #define C10_UNLIKELY(expr) (__builtin_expect(static_cast<bool>(expr), 0))
      |                                                                ^~~~
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/c10/util/Exception.h:441:7: note: in expansion of macro ‘C10_UNLIKELY_OR_CONST’
  441 |   if (C10_UNLIKELY_OR_CONST(!(cond))) {            \
      |       ^~~~~~~~~~~~~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:3:23: note: in expansion of macro ‘TORCH_CHECK’
    3 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                       ^~~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:5:24: note: in expansion of macro ‘CHECK_CUDA’
    5 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
/mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:21:2: note: in expansion of macro ‘CHECK_INPUT’
   21 |  CHECK_INPUT(vertices);
      |  ^~~~~~~~~~~
In file included from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/ATen.h:9,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/sdf/csrc/sdf_cuda.cpp:1:
/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:194:30: note: declared here
  194 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
g++ -pthread -shared -B /mnt/data3/HOME/zjx/miniconda3/compiler_compat -L/mnt/data3/HOME/zjx/miniconda3/lib -Wl,-rpath=/mnt/data3/HOME/zjx/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf/csrc/sdf_cuda.o /mnt/data3/HOME/zjx/code/PMnet_pytorch/outside-code/sdf/build/temp.linux-x86_64-3.7/sdf/csrc/sdf_cuda_kernel.o -L/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.7/sdf/csrc.cpython-37m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sdf
copying build/lib.linux-x86_64-3.7/sdf/csrc.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/sdf
copying build/lib.linux-x86_64-3.7/sdf/sdf.py -> build/bdist.linux-x86_64/egg/sdf
copying build/lib.linux-x86_64-3.7/sdf/sdf_loss.py -> build/bdist.linux-x86_64/egg/sdf
copying build/lib.linux-x86_64-3.7/sdf/__init__.py -> build/bdist.linux-x86_64/egg/sdf
byte-compiling build/bdist.linux-x86_64/egg/sdf/sdf.py to sdf.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdf/sdf_loss.py to sdf_loss.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/sdf/__init__.py to __init__.cpython-37.pyc
creating stub loader for sdf/csrc.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/sdf/csrc.py to csrc.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying sdf_pytorch.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sdf_pytorch.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sdf_pytorch.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sdf_pytorch.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
sdf.__pycache__.csrc.cpython-37: module references __file__
creating dist
creating 'dist/sdf_pytorch-0.0.1-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sdf_pytorch-0.0.1-py3.7-linux-x86_64.egg
removing '/mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/sdf_pytorch-0.0.1-py3.7-linux-x86_64.egg' (and everything under it)
creating /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/sdf_pytorch-0.0.1-py3.7-linux-x86_64.egg
Extracting sdf_pytorch-0.0.1-py3.7-linux-x86_64.egg to /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages
sdf-pytorch 0.0.1 is already the active version in easy-install.pth

Installed /mnt/data3/HOME/zjx/miniconda3/lib/python3.7/site-packages/sdf_pytorch-0.0.1-py3.7-linux-x86_64.egg
Processing dependencies for sdf-pytorch==0.0.1
Finished processing dependencies for sdf-pytorch==0.0.1`

**Comment by Kebii** [comment]
I have solved this problem.

change x.type().is_cuda() to x.is_cuda()
